# Generated by Django 3.0.4 on 2020-04-11 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('tagline', models.CharField(max_length=150, verbose_name='Слоган')),
                ('description', models.TextField(verbose_name='Описание')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='movie_thumbnail/')),
                ('year', models.PositiveIntegerField(default=0, verbose_name='Год выхода')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Добавлен на сайт')),
                ('country', models.CharField(max_length=150, verbose_name='Страна')),
                ('budget', models.PositiveIntegerField(default=0, verbose_name='Бюджет')),
                ('fees_in_usa', models.PositiveIntegerField(default=0, verbose_name='Сборы в США')),
                ('fees_in_world', models.PositiveIntegerField(default=0, verbose_name='Сборы в мире')),
                ('url', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Звезда рейтинга',
                'verbose_name_plural': 'Звёзды рейтинга',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=150)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie', verbose_name='Фильм')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.RatingStar', verbose_name='Звезда')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.CreateModel(
            name='MovieShots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='movie_shots/', verbose_name='Изображение')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movieshots_movie', to='movies.Movie', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Кадр из фильма',
                'verbose_name_plural': 'Кадры из фильма',
            },
        ),
        migrations.CreateModel(
            name='MoviePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('biography', models.TextField()),
                ('birthday_date', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='movie_persons/', verbose_name='Изображение')),
                ('as_actor', models.ManyToManyField(related_name='as_movie_actor', to='movies.Movie', verbose_name='Как актёр')),
                ('as_director', models.ManyToManyField(related_name='as_movie_director', to='movies.Movie', verbose_name='Как режиссёр')),
                ('as_producer', models.ManyToManyField(related_name='as_movie_producer', to='movies.Movie', verbose_name='Как продюсер')),
                ('as_scenarist', models.ManyToManyField(related_name='as_movie_scenarist', to='movies.Movie', verbose_name='Как сценарист')),
                ('genres', models.ManyToManyField(to='movies.Genre', verbose_name='Жанры')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='film_actors', to='movies.MoviePerson', verbose_name='Актёры'),
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='film_category', to='movies.Category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(related_name='film_directors', to='movies.MoviePerson', verbose_name='Режиссёры'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='film_genres', to='movies.Genre', verbose_name='Жанры'),
        ),
        migrations.AddField(
            model_name='movie',
            name='producers',
            field=models.ManyToManyField(related_name='film_producers', to='movies.MoviePerson', verbose_name='Продюсеры'),
        ),
        migrations.AddField(
            model_name='movie',
            name='scenarists',
            field=models.ManyToManyField(related_name='film_scenarists', to='movies.MoviePerson', verbose_name='Сценаристы'),
        ),
    ]
