# Generated by Django 3.0.4 on 2020-04-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieperson',
            options={'verbose_name': 'Участник кино', 'verbose_name_plural': 'Участники кино'},
        ),
        migrations.AlterField(
            model_name='movieperson',
            name='birthday_date',
            field=models.DateTimeField(default=0),
        ),
    ]
