# Generated by Django 3.0.4 on 2020-04-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200411_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieperson',
            name='biography',
            field=models.TextField(verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='movieperson',
            name='birthday_date',
            field=models.PositiveIntegerField(default=0, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='movieperson',
            name='genres',
            field=models.ManyToManyField(related_name='person_genres', to='movies.Genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='movieperson',
            name='height',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Рост'),
        ),
    ]
