# Generated by Django 3.0.4 on 2020-04-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200411_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='film_actors', to='movies.MoviePerson', verbose_name='Актёры'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='film_directors', to='movies.MoviePerson', verbose_name='Режиссёры'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='film_genres', to='movies.Genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='producers',
            field=models.ManyToManyField(blank=True, related_name='film_producers', to='movies.MoviePerson', verbose_name='Продюсеры'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='scenarists',
            field=models.ManyToManyField(blank=True, related_name='film_scenarists', to='movies.MoviePerson', verbose_name='Сценаристы'),
        ),
        migrations.AlterField(
            model_name='movieperson',
            name='as_actor',
            field=models.ManyToManyField(blank=True, related_name='as_movie_actor', to='movies.Movie', verbose_name='Как актёр'),
        ),
        migrations.AlterField(
            model_name='movieperson',
            name='as_director',
            field=models.ManyToManyField(blank=True, related_name='as_movie_director', to='movies.Movie', verbose_name='Как режиссёр'),
        ),
        migrations.AlterField(
            model_name='movieperson',
            name='as_producer',
            field=models.ManyToManyField(blank=True, related_name='as_movie_producer', to='movies.Movie', verbose_name='Как продюсер'),
        ),
        migrations.AlterField(
            model_name='movieperson',
            name='as_scenarist',
            field=models.ManyToManyField(blank=True, related_name='as_movie_scenarist', to='movies.Movie', verbose_name='Как сценарист'),
        ),
        migrations.AlterField(
            model_name='movieperson',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='person_genres', to='movies.Genre', verbose_name='Жанры'),
        ),
    ]
