# Generated by Django 3.0.4 on 2020-04-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200411_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieperson',
            name='gender',
            field=models.CharField(choices=[('MA', 'Мужчина'), ('FE', 'Женщина')], default='MA', max_length=2, verbose_name='Пол'),
        ),
    ]
